### PR TITLE
Update to v2.1.2 and remove special config for llvm

### LINKED ISSUE #42: Revert macOS LLVM 14 pinning
Once issue ( https://github.com/bacpop/pp-sketchlib/issues/92 ) is resolved, would revert commit ( https://github.com/conda-forge/pp-sketchlib-feedstock/pull/40/commits/c17c59dde8a7501697a62b191e444c7267fcdf70 ) and re-render

### PR DESCRIPTION
**Pull request by johnlees**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Fixes https://github.com/conda-forge/pp-sketchlib-feedstock/issues/42

Now upstream is fixed, I hope, can unpin llvm/clang versions and remove `libcxx`

### CODE REVIEW

**Comment by johnlees** [comment]
@conda-forge-admin, please rerender

**Comment by jakirkham** [comment]
Thanks John! 🙏

It looks like the version bump is missing from the changes

**Comment by jakirkham** [comment]
@conda-forge-admin , please re-render

**Comment by jakirkham** [comment]
@conda-forge-admin , please re-render

**Comment by jakirkham** [comment]
Manually added the migrator files from #45 , #46 and #47 as re-rendering won't add them alone. They come from [`conda-forge-pinning-feedstock`'s `recipe/migrations` directory]( https://github.com/conda-forge/conda-forge-pinning-feedstock/tree/main/recipe/migrations ) where all the migrators live (until they are completed at which point they are removed from that directory). Hope that is ok

**Comment by johnlees** [comment]
> Thanks John! 🙏
> 
> It looks like the version bump is missing from the changes

Forgot to actually commit the recipe!! Done now

**Comment by johnlees** [comment]
@conda-forge-admin, please rerender

**Comment by johnlees** [comment]
OS X failure:
```
import: 'pp_sketchlib'
Traceback (most recent call last):
  File "/Users/runner/miniforge3/conda-bld/pp-sketchlib_1703066779188/test_tmp/run_test.py", line 2, in <module>
    import pp_sketchlib
ImportError: dlopen(/Users/runner/miniforge3/conda-bld/pp-sketchlib_1703066779188/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/python3.8/site-packages/pp_sketchlib.cpython-38-darwin.so, 2): Symbol not found: _H5P_CLS_LINK_CREATE_ID_g
  Referenced from: /Users/runner/miniforge3/conda-bld/pp-sketchlib_1703066779188/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/python3.8/site-packages/pp_sketchlib.cpython-38-darwin.so
  Expected in: flat namespace
 in /Users/runner/miniforge3/conda-bld/pp-sketchlib_1703066779188/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/python3.8/site-packages/pp_sketchlib.cpython-38-darwin.so
```
May need patching in the CMakeLists.txt file

CUDA 12 issue is the same as before: https://github.com/conda-forge/pp-sketchlib-feedstock/issues/43. This has been fixed in the master branch of pybind11 but hasn't entered a release yet. So we'll need to keep gcc11 for now

**Comment by johnlees** [comment]
@conda-forge-admin, please rerender

**Comment by johnlees** [comment]
@conda-forge-admin, please rerender

**Comment by johnlees** [comment]
@jakirkham this is now all passing and ready to merge – would you mind just quickly checking all files/pinnings are as you'd expect

**Comment by jakirkham** [comment]
LGTM. Thanks for all your hard work on this John! 🙏

Added a fixes note in the OP for the macOS LLVM issue. Hope that is ok 🙂

**Pull request merged**
