### PR TITLE
Revert gcc pinning

### LINKED ISSUE #43: Revert GCC 11 Linux pinning
Once issue ( https://github.com/pybind/pybind11/issues/4606 ) is resolved, would revert commit ( https://github.com/conda-forge/pp-sketchlib-feedstock/pull/40/commits/68d36e69735c94bdbc826b0a9c73904fd2c15bc0 ) and re-render

### PR DESCRIPTION
**Pull request by johnlees**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Closes #43

### CODE REVIEW

**Comment by johnlees** [comment]
@conda-forge-admin, please rerender

**Comment by johnlees** [comment]
@conda-forge-admin, please rerender

**Comment by johnlees** [comment]
@jakirkham thanks for the ping on issue #43, looks like it's all working

**Comment by jakirkham** [comment]
Great, thanks John! 🙏

**Pull request merged**
